---
- name: Install mongodb
  become: true
  hosts: all
  tasks:
    - name: Add mongodb key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: EA312927

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Add mongo sources list
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present

    - name: Install mongo & update apt
      apt:
        name: mongodb-org
        state: present

    - name: Configure service
      systemd:
        name: mongod
        enabled: yes
