---
- name: Instal ruby & bundler
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install ruby
      apt: "name={{ item }} state=present"
      with_items:
        - ruby-full
        - ruby-bundler
        - build-essential
